label chapter03:
"Next day the sound of alarm woke me up,"
" my eyes were filled with triples after crying myself to sleep"
"I then checked a text I recieved it as info about location of Sphinx agency"
"I was confused for a second before remembering"
pov "ah, right... I go invited to join it."
"With a lazy sigh I got up and started getting ready"
"while doing so stumbling upon thing or two in the messy room"
"I went to the bathroom and brushed my teeth"
"then got ready and left the home locking it after and heading towards Sphinx agency"
"while playing music in my headphones."
" Once there I was greeted by Yume, she had her hair in buns and her blue eye color"
"and she wore same red dress as before"
"I didn't pay much attention and went to sit down to catch some breath when someone approached me and asked"
y  "may I sit here?"
"I glanced at the person and instantly nodded once seeing that it was Yume,"
"an idol that's part of Sphinx agency and stardust trio."
pov "Sorry, I didn't saw you come by."
"I said looking down I could feel her gentle smile look down at me..."
"it reminded me of Avaline... I miss her so much"
y "Hey, are you alright?"
"She asked her smile twisting to one of worry I gave out a nod and sighed before speaking"
pov "I'll be fine... "
pov "it's just... a lot is happening at same time." 
"She gave me a sympathetic look as she then spoke"
y "if you say so... just so you know you aren't alone."
"She gave me a half smile that already told me that she could be trusted I too returned the smile and thinking"
"that she reminded me of Avaline... shaking my head and trying to clear my thoughts"
" I started looking around the building that was full of colors and lively people"
"but in a way.... it all honestly felt forced..."
y "Yo, you look kinda stressed and overwhelmed...." 
"Yume noted her blue eyes staring in my yellow eyes"
"making me uncomfortable in a way more like nervous so I spoke:"
pov "I mean this is is my first time actually joining an agency."
"Yume gave me a warm smile and spoke"
y  "well in that case come on I'll guide you to the room where your final round before joining Sphinx begins!" 
"She said grabbing my hand and dragging me along"
"inside the office a woman with her hair tied in a bun and working outfit sat on a chair"
"before getting up and greeted me after some talking and paper signings"
"I thanked the lady and went outside where Yume was waiting for me"
y "hey, did you read the papers carefully?"
"she rendomly asks"
pov "yeah I did why?"
"I ask her locking my eyes with hers"
y "they tend to hide somethings that are harsh for people using their tos and those that work here"
"she says"
y "so do be careful please. You might get blackmailed…"
"she mutters her face looking gloomy for a second before it shifted as she spoke"
y "anyway! You already know Kage and Aoi up close let’s go meet rest!"
"she said grabbing my arm and dragging me to her friend group"
y "guys meets [player_name]! Shiro please be a bit gentle with them"
"she paused the introduction"
"Shiro, one with white hair and hazel eyes leaned back against the wall near her and crossed her arms and spoke"
S  "pffft, yeah right keep dreaming,"
"she said leaning against the wall her hazel eyes beaming with mischief Yume let out a shigh and whispered to me"
y "Hey, if she ever does something harsh,"
y "like bullying or anything like that, just let me or Yuki know."
y "She tends to either listen to me or Yuki."
y "You see, she hates it when Yuki gets angry; it’s like watching a cat try to avoid a bath!"
"I nod honestly not even caring if I’d be bullied or not I’m used to that sh--."
"Just then, Shiro’s ears perked up, and her smirk flipped upside down."
S "HEY, I AM NOT!"
"she shouted, her voice echoing off the walls. The sudden outburst made Yume jump, but she quickly burst into laughter."
"In main time on the corner of an eye I saw an angry white haired"
"and blue eyed fashionista chihuahua give a loud breath in and out as she too let out a loud "
Y "QUIET"
"Shiro winced in shock, her bravado crumbling as she immediately stopped her playful banter."
S "Uh, sorry, Yuki!"
"she stammered, her tough-guy act fading away. Yuki, the fashionista cousin, shot Shiro a look that could freeze fire."
"Yume doubled over with laughter," 
"clutching her stomach I too let out a small chuckle"
"as I glanced to see all eyes were on us, I mean with all that shouting it’s no wonder."
"Yume, while watching Yuki scold her cousin, was in the middle of a laughing fit."
y "W-welcome to the…"
"she gasped between giggles,"
y "chaos!" 
y "Oh lord,"
"she continued, her laughter bubbling over."
"Hahaha! I can’t stoooopppppp!"
"Shiro, trying to regain her composure, couldn’t help but join in."
S "You’re going to make me cry, Yume! I’m just trying to defend my honor here!"
"Yuki, arms crossed and still wearing her fierce expression, couldn’t hold back a smile."
Y "you call this defending your honor? You’re just giving me more material for my fashion critiques!"
"she said with half sarcasm and half annoyance"
S "Hey, I’m a trendsetter!"
"Shiro shot back, puffing out her chest dramatically."
S "You should be taking notes instead of critiquing me!"
"Yuki rolled her eyes, but the corners of her mouth twitched upward."
Y "Trendsetter? More like a walking disaster!"
"Shiro gasped dramatically making Yume burst into more laughter if that was possible"
"Shiro gasped dramatically, clutching her heart as if Yuki had dealt a fatal blow."
S "How dare you! I’ll have you know that my unique style is all the rage in the land of Chaosville!"
"Shiro said and while kept on throwing"
"more and more talk backs back and fourth and Yume crying from laughter As the laughter echoed through the agency's bustling workspace,"
"Miru, with her dark skin and black hair tied in two playful buns, sighed dramatically."
M"Cut it out, you two! You’re making Yume die from laughter, and all eyes are on you!"
"Yume, still giggling, managed to gasp,"