label chapter03:
"Next day the sound of alarm woke me up,"
" my eyes were filled with triples after crying myself to sleep"
"I then checked a text I recieved it as info about location of Sphinx agency"
"I was confused for a second before remembering"
pov "ah, right... I go invited to join it."
"With a lazy sigh I got up and started getting ready"
"while doing so stumbling upon thing or two in the messy room"
"I went to the bathroom and brushed my teeth"
"then got ready and left the home locking it after and heading towards Sphinx agency"
"while playing music in my headphones."
" Once there I was greeted by Yume, she had her hair in buns and her blue eye color"
"and she wore same red dress as before"
"I didn't pay much attention and went to sit down to catch some breath when someone approached me and asked"
y  "may I sit here?"
"I glanced at the person and instantly nodded once seeing that it was Yume,"
"an idol that's part of Sphinx agency and stardust trio."
pov "Sorry, I didn't saw you come by."
"I said looking down I could feel her gentle smile look down at me..."
"it reminded me of Avaline... I miss her so much"
y "Hey, are you alright?"
"She asked her smile twisting to one of worry I gave out a nod and sighed before speaking"
pov "I'll be fine... "
pov "it's just... a lot is happening at same time." 
"She gave me a sympathetic look as she then spoke"
y "if you say so... just so you know you aren't alone."
"She gave me a half smile that already told me that she could be trusted I too returned the smile and thinking"
"that she reminded me of Avaline... shaking my head and trying to clear my thoughts"
" I started looking around the building that was full of colors and lively people"
"but in a way.... it all honestly felt forced..."
y "Yo, you look kinda stressed and overwhelmed...." 
"Yume noted her blue eyes staring in my yellow eyes"
"making me uncomfortable in a way more like nervous so I spoke:"
pov "I mean this is is my first time actually joining an agency."
"Yume gave me a warm smile and spoke"
y  "well in that case come on I'll guide you to the room where your final round before joining Sphinx begins!" 
"She said grabbing my hand and dragging me along"
"inside the office a woman with her hair tied in a bun and working outfit sat on a chair"
"before getting up and greeted me after some talking and paper signings"
"I thanked the lady and went outside where Yume was waiting for me"
y "hey, did you read the papers carefully?"
"she rendomly asks"
pov "yeah I did why?"
"I ask her locking my eyes with hers"
y "they tend to hide somethings that are harsh for people using their tos and those that work here"
"she says"
y "so do be careful please. You might get blackmailed…"
"she mutters her face looking gloomy for a second before it shifted as she spoke"
y "anyway! You already know Kage and Aoi up close let’s go meet rest!"
"she said grabbing my arm and dragging me to her friend group"
y "guys meets [player_name]! Shiro please be a bit gentle with them"
"she paused the introduction"
"Shiro, one with white hair and hazel eyes leaned back against the wall near her and crossed her arms and spoke"
S  "pffft, yeah right keep dreaming,"
"she said leaning against the wall her hazel eyes beaming with mischief Yume let out a shigh and whispered to me"
y "Hey, if she ever does something harsh,"
y "like bullying or anything like that, just let me or Yuki know."
y "She tends to either listen to me or Yuki."
y "You see, she hates it when Yuki gets angry; it’s like watching a cat try to avoid a bath!"
"I nod honestly not even caring if I’d be bullied or not I’m used to that sh--."
"Just then, Shiro’s ears perked up, and her smirk flipped upside down."
S "HEY, I AM NOT!"
"she shouted, her voice echoing off the walls. The sudden outburst made Yume jump, but she quickly burst into laughter."
"In main time on the corner of an eye I saw an angry white haired"
"and blue eyed fashionista chihuahua give a loud breath in and out as she too let out a loud "
Y "QUIET"
"Shiro winced in shock, her bravado crumbling as she immediately stopped her playful banter."
S "Uh, sorry, Yuki!"
"she stammered, her tough-guy act fading away. Yuki, the fashionista cousin, shot Shiro a look that could freeze fire."
"Yume doubled over with laughter," 
"clutching her stomach I too let out a small chuckle"
"as I glanced to see all eyes were on us, I mean with all that shouting it’s no wonder."
"Yume, while watching Yuki scold her cousin, was in the middle of a laughing fit."
y "W-welcome to the…"
"she gasped between giggles,"
y "chaos!" 
y "Oh lord,"
"she continued, her laughter bubbling over."
"Hahaha! I can’t stoooopppppp!"
"Shiro, trying to regain her composure, couldn’t help but join in."
S "You’re going to make me cry, Yume! I’m just trying to defend my honor here!"
"Yuki, arms crossed and still wearing her fierce expression, couldn’t hold back a smile."
Y "you call this defending your honor? You’re just giving me more material for my fashion critiques!"
"she said with half sarcasm and half annoyance"
S "Hey, I’m a trendsetter!"
"Shiro shot back, puffing out her chest dramatically."
S "You should be taking notes instead of critiquing me!"
"Yuki rolled her eyes, but the corners of her mouth twitched upward."
Y "Trendsetter? More like a walking disaster!"
"Shiro gasped dramatically making Yume burst into more laughter if that was possible"
"Shiro gasped dramatically, clutching her heart as if Yuki had dealt a fatal blow."
S "How dare you! I’ll have you know that my unique style is all the rage in the land of Chaosville!"
"Shiro said and while kept on throwing"
"more and more talk backs back and fourth and Yume crying from laughter As the laughter echoed through the agency's bustling workspace,"
"Miru, with her dark skin and black hair tied in two playful buns, sighed dramatically."
M"Cut it out, you two! You’re making Yume die from laughter, and all eyes are on you!"
"Yume, still giggling, managed to gasp,"
y "But it’s so funny! I can’t help it!"
"Miru rolled her eyes and sighed"
M  "and here I was told to be the one that delayed stuff the most due to my nature of focusing on one thing "
M "when I start it but what are you three doing making newbie get filled up with all this chaos,"
M "right on their first day of work?"
"Yuki let out a sigh in and out and agreed with Miru not apologizing or anything"
"but taking responsibility to calm down and continue the argument later"
"but Shiro wasn’t done it seemed cause she said"
S "hah! Loser!"
"making Yuki go up to her give her a piercing glare and shutting her up as Yume’s laughter too calmed down"
"As Yuki shot Shiro a piercing glare,"
"the atmosphere shifted dramatically. Shiro’s confident smirk faltered,"
S "Whoa, whoa, Yuki! No need to unleash the death stare! I’m just kidding!"
" as she gulped and gave out a nervous chuckle."
"She held up her hands in surrender, her white hair framing her face like a startled cat."
"Yume burst into laughter, unable to contain herself."
y "Shiro, you look like you just saw a ghost! Relax, she’s not actually going to turn you into a statue… yet."
"Miru chuckled, shaking her head."
M "You really should know better than to poke the bear, Shiro. Yuki’s glare is legendary!"
S "Legendary? More like terrifying!"
"Shiro exclaimed, her voice a mix of exasperation and amusement."
S "I swear, every time she looks at me like that, I feel like I’m about to be sent to the Shadow Realm!"
"Yuki couldn’t help but crack a smile, the tension easing as she saw Shiro’s exaggerated reaction."
Y "Alright, alright, I’ll ease up on the glare… for now," 
"she said, trying to sound serious but failing miserably."
S "Phew! Thank you!" 
"Shiro sighed dramatically, placing a hand over her heart as if she had just survived a near-death experience."
S "Now, back to the back to our next fashion show... How about we make it a ‘Survival of the Fittest’ theme?"
S "I could use some practice dodging glares…” she said still cooling down from Yuki’s glare"
"Yume rolled her eyes, still giggling."
y "Only if you promise to wear a ‘I Survived Yuki’s Glares’ t-shirt during the event!"
y "anyway I still have to introduce [player_name] to others too you three have fun planning!"
"she said grabbing my hand and forgetting to introduce myself to Miru but shhhh… no one tell her…"
"as we walked away from the trio their chatter could still be heard"
"and almost everything that screamed happiness felt forced to me"
"other than the three’s laughter maybe"
"if Avaline was here she’d help me understand the environment better…"
"I miss her…"
y "hey are you okay?"
"Yume asked looking me in the eyes I give out a nod as she sighed and said"
y "you know, I’m sure she’s watching you from the skies so maybe for her try to move on?"
"she said gently as I glanced at the sky and smiled a little,"
"she was right Avaline wouldn’t like seeing me sad"
y "let’s go meet the rest of the group! They aren’t as chaotic as the other!"
"she said her face beaming with joy I let out a chukle and smiled"
pov "alright, lead the way princess"
"I say making her giggle as she dashed through the halls of the huge agency’s office"
"as I followed with fast steps her telling me to hurry up but me taking my own pace"
"The walls were adorned with colorful posters showcasing various projects,"
"and the air buzzed with the chatter of colleagues brainstorming ideas. It felt like stepping"
"into a world of creativity and collaboration, and I couldn’t help but smile at the lively atmosphere."
"As we rounded a corner, Yume paused dramatically,"
"striking a pose as if she were about to unveil a grand surprise."
y "And here we are!"
"she announced, gesturing to a cozy lounge area where a few familiar faces were gathered."
"On a chair sat a with striking cyan hair,"
"her pencil dancing across the page as she focused intently on drawing a manga character."
"She was so engrossed in her work that she hadn’t noticed Yume and me yet. Next to her,"
"another girl with brown hair tied up in two playful pigtails was flipping through a script,"
"her brow furrowed in concentration as she practiced lines for an upcoming project."
"Yume huffed not liking how her dramatic appearance didn’t catch the twos eyes"
"so with a playful shout she said"
y "Tsuki! Hoshi! Look what the cat dragged in!"
"she said making cyan haired girl squeal and jump in her seat"
"ruining her manga chapter a little"
"and girl with pigtails looking up with confusion and curiosity half smirk on her face"
T "Y-Yume! You ruined my a-art!"
"with frusturation and worry girl with cyan hair stated"
"before her eyes turned to me as she shyly ducked her head and muttered"
T "I-I'm sorry...."
"while the other chukled at the others misery and spoke"
H "as careless as ever I see."
"Yume’s playful demeanor faltered as she noticed Tsuki’s tired expression,"
"her usual spark dimming in the face of the looming deadline."
y "Oopsiees…"
"she said, her voice light but tinged with guilt,"
"as if that could somehow erase the chaos she had caused."
"I watched Tsuki, her shoulders slumped and eyes heavy with fatigue."
"The pressure was palpable, and it was clear she was already feeling the weight of the world on her shoulders."
y "Really, I’m sorry! Is there any way I could help?"
"Yume’s tone shifted from upbeat to genuinely concerned, her eyes wide as she took in Tsuki’s state."
T "please just leave me to it alone okay?"
"she said in a very silent tone her eyes getting filled with tears"
"Tsuki glanced up, her expression a mix of frustration and exhaustion."
T "I’ll be fine!… I-I will just redo it no worries!- I’ll be the one getting scolded anyway..." 
"She trailed off, her voice barely above a whisper as she gestured to the mess of scribbles on her page."
"I could see the tension in Tsuki’s posture,"
"the way her fingers fidgeted with the edge of her sketchbook."
"It was clear from her body language that she was overwhelmed. Yume must have sensed it too,"
"as her usual bubbly energy was replaced by a sincere desire to help."
"Suddenly the one with pigtails got up"
"as if tired from all this and started heading out in another direction while Aoi,"
"Kage and Yume tried to calm Tsuki down as I heard her name was"
pov "hey where are you going uh-"
"she paused others not paying much attention to us now as she spoke"
H "It’s Hoshi and I’ll tell the CEO to give Tsuki more time on her deadline"
"she said calmly"
pov "will the CEO listen though?"
"I ask as she chuckled and looked at me as she said"
H "of course, I’m his one and only daughter dearest"
"her words took me by surprise and as "
"I was about to confirm info I just got she was already far from the place I was in"
"I stayed with Tsuki and tried to calm her down"
"with Kage going to call Shiro over to let her help Tsuki with drawing"
"Yuki getting dragged alongside her cousin while no one seemed to notice Hoshi no longer begin around… "
"that was odd… do they hate her?"
"As we warped up the chapter Tsuki was working on she thanked everyone and we parted ways "
"after the work was done with Yume walked me out of the agency as she spoke"
y "hey… I’m sorry about all that."
"she looked down feeling upset over events that occoured"
pov "no worries at least the chapter turned out even bettter than before."
"I gently smiled Yume’s sad face beaming with joy again"
y "I guess your right!" 
y "also… stay away from Hoshi, I heard she’s a huge trouble…"
"she trailed off"
y "she is rumured to be dating older man and CEO also seems to faviour her,"
y "which is never a good sign so do stay away okay? For your own sake…"
"she said her face full of worry so to reassure her I smiled and spoke"
pov "I’ll try."
"Yume smiled and spoke"
y "well see you tomorrow!"
pov "see ya."
"I say waving my hand and walking away"