define B = Character("bully #1")
define b = Character("Bully #2")
define u = Character("???")

label chapter02:
"it had been a few days sence Avaline"
"I've been lacking in studies a little"
"due to remembering her and how she..."
"I keep on remembering her during those days"
"I miss her presence,"
"her style of clothing..."
"its been rough these days..."
"even something I was numb to made me angry"
"I would always ignore those two girls in my class all the time"
"making them mad enough to leave me alone for some time."
"but now..."
"I was sitting at my desk finishing the assignment last minute"
"when the girl with two buns, rose pins, blue jacket and short skirt came up to me"
"and snatched my notebook away"
B "oops! this assignment sure is important to you..."
B "am I rightttttt?"
"she teases"
pov "HEY!"
pov "GIVE THAT BACK!"
"I stand up and reached for the notebook only for her to step away and make me stumble over my feet"
"I then got up and chased after her recklessly kick down the items blocking my way"
"eventually she trips and I get my notebook back while her minion checks up on her while I roll my eyes"
"and deadpanningly say"
pov "don't even bother pempering her"
pov "she only tripped is all."
"I sat back on my desk and continued my assigment and"
"after all that the teacher finally comes and I hans over my assigment"
"as I get to my desk I see her glaring at me"
"while her minion looked nervious"
"I ofcourse didn't care at all and sat down."
#bg change here too
"after school I went home as usual"
"but I couldn't stop thinking about the day Avaline..."
"..."
"ever sence then she has been in my head for days"
"I couldn't focus on anything"
"not even music could help me focus on what I had to do..."
"I would remember way she smiled,"
"and how she'd she'd talk to me..."
"..."
"I guess this is what happens when two best friends are seperated huh?..."
#bg change will go here
"at home"
"I was watching TV, seeing the concert Avaline loved watching"
"more than me..."
pov "Sphinx Agency... what a tacky name."
pov "oh well..."
"I turned off the TV as I went outside"
"passing by each building until I realised I walked too far"
"but whatever, nothing is suprising..."
"as I was walking down the streets I heard three girls passing by"
"I recodnize their voices and lifted my head to look"
"as they were going to walk by they had noticed me"
"one of the girls with pink pastel hair and pastel goth outfit came a lilttle close and asked me"
#aoi's pic will go here
u "you look gloomy what's up with you?"
"I don't feel comfrtable with this question"
"It's only been days yetI've been losing my head about Avaline..."
"...Ava"
"..."
"dang it,"
"I look like a messy wimp at this point..."
#yume pic goas hereeee
u "um.. I think they're uncomfortable with your question, they look like they've been going through something."
"the girl said. as those two were talking the third girl didn't utter a word"
menu:
 "ask if she's okay":
  "this will be updated soon"
 "not ask anything":
  "I shouldn't ask if she's okay out of the blue, it'll be rendom"

"soon enough black haird girl called out to me"
u "hey what's your name? my name is Yume, Yume Hoshino"
"she said with a smile,"
"she looks like dreamy type."
"I guess it won't hurt to say my name."
menu:
 "my name is":
  "my name's [player_name]"

"I anwser Yume."
"she looked enlighted to hear that"
"that's a relief"
y "oh, right meet the others!"
"she says pointing to one with pastel pink hair"
#Aoi's pic goes here
y "this Aoi, Aoi Akari"
y "and that is Kage Akari!"
"well at least I get to know their names"
pov "Well, that's nice. I'm happy to meet you guys"
"I tell them"
pov "but I'm planning on going home sooner so."
"I add on,"
#Yume pic here
"Yume gets a little sad considering she wanted to talk more with me."
y "Well, see you later new-face!"
"I wave at her and walk to my home."
#bg change here
"at home I was sitting in bed as I fel lonliness dig deep into me"
"I miss Avaline..."
"I miss her too much"
"My heart was only half when she complited it..."
"Before I knew it, I started having a panic attack when remembering Avaline"
"she was the only girl in my life who treated me like a human. . "
"Without her, who would be the one to comfort me when I'm at my lowest..? She was like a mother to me,"
"i couldn't do anything to make her more happy?"
"She was the one who was making me happy and i really couldn't do anything for her..? "
"She always was like a guardian to me. I look at the items that would remind me of her, it made it slightly better or so.."
"which was kind of sad realizing only Avaline was the girl who'd come to help.. "
"everyone else would’ve just ignored me or make fun of me if they saw me like  this..."
"..4:37 AM, I slept crying. I go change and go on a walk,"
"the air seems cold today. Either that or I'm just imagining it was. I sit at the park bench,"
"thinking about my memories with Avaline. "
"As I did so, someone behind me laid their hands on the bench and looked at the sky. I looked to see who it was."
"it was Yume."
y "Look at the clouds! aren't they pretty?"
"Yume asks while looking at the clouds."
pov "...yeah."
"I look at the clouds aswell,"
"we shared a quiet moment together that had lasted for quite a few minutes. Yume had interrupted the quiet moment."
y "do you want to join Sphinx agency?"
"She asks. I was quite surprised by the sudden offer to the point I let out a"
pov "HUH?"
"sound out of instinct."
"She was quite shocked by the sudden sound but chuckled,"
y "pretty random to ask you, that's understandable." 
y "I saw you during the audition with a girl but then found out what happened to her."
y  "It was really sad to hear though, kage was the one to inform me about it." 
"She added on, she looked down while in such a gloomy face."
y "you must've been really great friends with her."
"it was true, we were great friends."
"our friendship simply felt so short. "
pov "we were."
"I replied, we both shared a quite moment again. A few minutes later.. I've been thinking about her offer, I look at her."
pov "hey.. about your question about joining the agency.." 
"I say, hesitating. she turned to look at me with a curious look."
pov "I'll accept."
"I say, she was quite enlightened."
y "REALLY?!"
pov "i figured.. Avy would've been happy for me if I joined on her behalf,"
pov "she gets proud of me when I follow her footsteps."
"I tell her,"
y  "like a mother!" 
"she comments, she's not wrong though. Avaline was there for me almost my whole life if I can recall."
pov "The clouds are pretty."
"I said"
"I'm sure Avy is so happy jumping on clouds for the first time."

jump chapter03