label chapter04:
"Next day at the agency everyone was moving from left to right chatting and working "
"as I stood in place wondering what was going on, as Hoshi approached me holding stuff in her arms as she spoke"
H "ah, hello newbie"
"she greeted me"
pov "hi Hoshi, what is going on?"
"I ask her sighing and saying"
H "my dad dropped a surprise festival idea on us at really rendom time for Halloween,"
H "we only have a week to prepare with loads of activities to plan out"
"she says "
"I pause surprised by this, if I remember correct Avaline said that every months"
"celebration done by Sphinx Agency lasts for days, so shouldn’t they have been informed a bit sooner?"
"I grabbed some of Hoshi’s stuff after offering her help as I asked"
pov "hey just a question but how long does each of events the agency prepares takes?"
"Hoshi locked her eyes with mine before looking at the boxes as she speaks"
H "up to at the very least six to eight months"
"and the CEO expects us… to finish it all in a week? I thought to myself that’s absurd."
"After helping Hoshi"
"I stumbled upon Tsuki who seemed to be struggling with a"
"drawing as she kept on erasing facial expressions of some anime characters and looking extremely tired"
pov "you don’t seem to be doing so well are you the only one working on that project? You really need some rest."
"I say concerned about her psychical and psychological state."
"She jolted at my sudden voice turning her face from computer to me as she stumbled upon her own words as she spoke"
T "ah! Sorry I didn’t notice you coming!-"
"she paused looking at me with apologetic look "
pov "it’s okay happens to the best of us."
"I assure her as she gives me a small smile before she goes back to drawing while she speaks"
T "I had three assistants helping me out..."
T "but eventually one went missing and the other’s health is in shambles so I’m doing all this alone…"
"I paused not sure how to respond but my mind and heart are not on same path as I spoke"
pov "hey, I don’t have much experience with drawing manga but I can try,"
pov "you REALLY need to rest I can tell you were already skipping sleep much longer than a week."
"Tsuki paused glancing at me in confusion before smiling and saying"
T "I-I wouldd apreterit it... but you don’t have to, plus I’m fine I can just buy coffee or something"
"too late Tsuki, your stubbornness won’t help ya I think to myself before I speak"
pov "Tsuki, I’m going to help and no isn’t going to be accepted."
T "but!-"
"she kept on going but I shushed her putting my finger over her mouth to silence her my face twisting into a smug grin"
pov "no buts."
"I say making her instantly go silent then give out a defeated sigh and agreed to let me help her."
"HAH I win! Even Avy couldn’t beat me at begin stubborn…"
"I shook my head waving that tought away as I sat down next to Tsuki opening up the app she was using to draw"
pov "so what part of story did stop on? I’ll do the characters because I’m not good at it"
"I say Tsuki smiling a little as she spoke"
T "t-that’s okay! I’ll do the backgrounds as for where I stopped"
T "is on main characters brother begin burnt to crisp as he had powers of destruction."
pov "I see…"
"I say quickly sketching the drawing and after quite some time I finish as I say"
pov "something like this?"
"Tsuki looks at my drawing to see the anatomy completely messed up and the character looking mostly cartoonish,"
"she lets out a small chuckle noticing how badly out of place hair was as well as she spoke"
T "um... how about you use shapes for the body then draw the head after?” she suggests"
pov "got it my queen!"
"I playfully stated making Tsuki chuckle before gave me a small, shy smile "
"after that we both begin working on our project her giving me tips, "
"encouraging me and helping me while I made her laugh over some comedies I knew of"
"and plenty more in the end wrapping up the chapter with greatest plot twist of all "
"time by revealing where the saint’s brother went after begin burnt to crisp we were both"
"laughing and chatting not realizing that the app glitched and instantly closed leaving us both confused"
"but not worried about losing the files"

scene black

"In the shadows, none ever knew, " 
"Stood a figure, cloaked in rue. " 
"Only silence dared to creep, "
"While secrets whispered, buried deep."
"A lifeless form, cold as stone, " 
"What sins were wrought? What truth unknown? "
"Who is this ghost that haunts the night? " 
"What dark deeds led to this blight?  "
"Shhh… listen close, for the answer’s near,  "
"In the silence, the truth is clear"