label chapter03:
"Next day the sound of alarm woke me up,"
" my eyes were filled with triples after crying myself to sleep"
"I then checked a text I recieved it as info about location of Sphinx agency"
pov "ah, right... I go invited to join it."
"With a lazy sigh I got up and started getting ready"
'while doing so stumbling upon thing or two in the messy room"
"I went to the bathroom and brushed my teeth"
"then got ready and left the home locking it after and heading towards Sphinx agency"
"while playing music in my headphones."
" Once there I was greeted by Yume, she had her hair in buns and her blue eye color"
"and she wore same red dress as before"
"I didn't pay much attention and went to sit down to catch some breath when someone approached me and asked"
y  "may I sit here?"
"I glanced at the person and instantly nodded once seeing that it was Yume,"
"an idol that's part of Sphinx agency and stardust trio."
pov "Sorry, I didn't saw you come by."
"I said looking down I could feel her gentle smile look down at me..."
"it reminded me of Avaline... I miss her so much"
y "Hey, are you alright?"
"She asked her smile twisting to one of worry I gave out a nod and sighed before speaking"
pov "I'll be fine... "
pov "it's just... a lot is happening at same time." 
"She gave me a sympathetic look as she then spoke"
y "if you say so... just so you know you aren't alone."
"She gave me a half smile that already told me that she could be trusted I too returned the smile and thinking"
"that she reminded me of Avaline... shaking my head and trying to clear my thoughts"
" I started looking around the building that was full of colors and lively people"
"but in a way.... it all honestly felt forced..."
y "Yo, you look kinda stressed and overwhelmed...." 
"Yume noted her blue eyes staring in my yellow eyes"
"making me uncomfortable in a way more like nervous so I spoke:"
pov "I mean this is is my first time actually joining an agency."
"Yume gave me a warm smile and spoke"
y  "well in that case come on I'll guide you to the room where your final round before joining Sphinx begins!" 
"She said grabbing my hand and dragging me along"
"inside the office a woman with her hair tied in a bun and working outfit sat on a chair"
"before getting up and greeted me after some talking and paper signings"
"I thanked the lady and went outside where Yume was waiting for me"
y "hey, did you read the papers carefully?"
"she rendomly asks"
pov "yeah I did why?"
"I ask her locking my eyes with hers"
y "they tend to hide somethings that are harsh for people using their tos and those that work here"
"she says"
